feature/PROD-6398
cv-library/vagelis-ilias-favourite-colours pull request #1
Opened 2024-05-28 10:15 UTC by vagelisIlias

## Description

Setup environment and dependencies

![Screenshot from 2024-05-28 11-09-42](https://github.com/cv-library/vagelis-ilias-favourite-colours/assets/70903591/c1c3b8c8-3114-4ec3-9579-684268fff3d0)

![Screenshot from 2024-05-28 11-10-31](https://github.com/cv-library/vagelis-ilias-favourite-colours/assets/70903591/35c7f377-91fc-4a2d-a69e-80a98a163dbe)

## Issue

Link to the issue or bug that this pull request addresses, if applicable.

## Test Plan

Please describe the steps you took to test these changes, and the expected outcome.

## Additional Context

Please provide any additional context or information that may be useful in reviewing this pull request.

## Checks

- [x] Did you test this locally?
- [] Did you add unit tests based on the feature implemented?

2024-05-28 12:37 UTC, ChezGray123 approved these changes

2024-05-28 12:38 UTC, anthophobiac commented
@vagelisIlias Just for information, it's best to have the actual Jira ticket number present in the branch name (so feature/PROD-6398) :)

2024-05-28 12:40 UTC, adrian-marinescu-ch commented on .env
> -CORS_ALLOW_ORIGIN='^https?:\/\/([a-zA-Z0-9-]+\.)*resume-library\.com(:[0-9]+)?$'
@vagelisIlias if you don't need to keep account for CORS requests, you might need to remove the composer package `nelmio/cors-bundle` as well as it might crash the app other wise..basically rollback parts of https://github.com/cv-library/php-symfony-skeleton/pull/29 in your PR

2024-05-28 12:43 UTC, adrian-marinescu-ch requested changes
check comments above ^

2024-05-28 13:27 UTC, vagelisIlias commented on .env
> -CORS_ALLOW_ORIGIN='^https?:\/\/([a-zA-Z0-9-]+\.)*resume-library\.com(:[0-9]+)?$'
removed the package now and from composer.json

2024-05-28 13:27 UTC, vagelisIlias commented on docker-compose.yml
> +      - "traefik.http.routers.fav_colours.rule=Host(`fav_colours.test`)"
Took off the ``, that would be an issue

2024-05-28 13:34 UTC, vagelisIlias commented on docker-compose.yml
> +      - "traefik.http.routers.fav_colours.rule=Host(`fav_colours.test`)"
i saw the comments, is the fav_colours going to conflict as i a bit different from the link sent me above

2024-05-28 13:46 UTC, adrian-marinescu-ch commented on .env
> -CORS_ALLOW_ORIGIN='^https?:\/\/([a-zA-Z0-9-]+\.)*resume-library\.com(:[0-9]+)?$'
what about `README.md`, `composer.lock`, `config/bundles.php`, `config/packages/nelmio_cors.yaml` and `symfony.lock`. Please check the linked PR from my comment to be sure you removed everything related to this. Also when removing composer packages please do via composer remove not by manually editting composer.json so the composer.lock is up-to-date with the right deps. Thx!

2024-05-28 13:48 UTC, adrian-marinescu-ch commented on docker-compose.yml
> +      - "traefik.http.routers.fav_colours.rule=Host(fav_colours.test)"
now you have a conflict with @anthophobiac project that uses the same host as you, please use a different one from both @anthophobiac & @kimberlyeslami

2024-06-03 09:39 UTC, adrian-marinescu-ch approved these changes

2024-06-04 11:57 UTC, isiupik approved these changes

2024-06-04 11:58 UTC, merged